### ISSUE TITLE
why is this great app not in google play anymore? 

### ISSUE THREAD

**Issue by rvdwijngaard** [leinardi/KitchenTimer#1]
I love this app! unfortunately I can no longer download it from google play store.

**Comment by leinardi** [comment]
Hi @rvdwijngaard, unfortunately I have no time to maintain the app anymore and Google decided to remove it.
If you are interested in a good alternative, Google released a very good [Desk Clock app](https://play.google.com/store/apps/details?id=com.google.android.deskclock) that has also a count down feature.

But if you need the APK of my original app, I have attached it to the release v1.2.0: https://github.com/leinardi/KitchenTimer/releases/tag/v1.2.0

**Comment by rvdwijngaard** [comment]
One of the great things of your app is the presets. I have downloaded and installed the apk. thanks!
